name: Compilation Testing for DYAD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    strategy:
      matrix:
        base-os:
          - focal
          - fedora38
          - fedora35
          - el8
          - el7
        flux-version:
          - v0.52.0
          - v0.51.0
          - v0.50.0
          - v0.49.0
          - v0.48.0
    runs-on: ubuntu-20.04 # Docker-based jobs must run on Ubuntu
    if: ${{ matrix.base-os != 'fedora38' || contains(fromJSON('["v0.52.0", "v0.51.0"]'), matrix.flux-version) }}
    container: fluxrm/flux-core:${{ matrix.base-os }}-${{ matrix.flux-version }}
    steps:
      - uses: actions/checkout@v2

      - name: Run autogen
        run: ./autogen.sh

      - name: Configure build
        run: ./configure --enable-dyad-debug CC=$(which gcc) CXX=$(which g++)

      - name: Build DYAD
        run: make -j
